name: dicomhandler

# este workflow se ejecuta para cada una de estas acciones que uno lista acá
on:
	- push
	- pull_request

jobs:
	build:

		runs-on: ubuntu-lastest
		strategy:
		matrix:
			python-version: [3.7,3.8,3.9,3.10,3.11]

		steps:
			- uses: actions/checkout@master
			- name: Set up Python ${{ matrix.python-version}}
			  uses: actions/setup- python@v2
			  with:
					python-version: ${{matrix.python-version}}
			- name: Install tox
			  run: pip install tox tox-gh-actions
			- name Test with tox
			  run: tox -r
			- name Test Coverage
			  if: ${{ matrix.python-version == '3.10' }}
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
				run: |
					pip install coveralls
					coveralls --service=github